// Generated by https://quicktype.io

import { ProductCart } from "./CartType";

export interface PaymentResponseType {
    order: OrderPaymentResponseType;
}

export interface OrderPaymentResponseType {
    totals:              TotalsPaymentResponse;
    id_address_invoice:  string;
    id_address_delivery: string;
    subtotals:           SubtotalsPaymentResponse;
    products_count:      number;
    shipping:            { [key: string]: string }[];
    products:            Products;
    amounts:             AmountsPaymentResponse;
    details:             DetailsPaymentResponse;
    history:             HistoryPaymentResponse;
    messages:            any[];
    carrier:             CarrierPaymentResponse;
    addresses:           AddressesPaymentResponse;
    follow_up:           string;
    labels:              LabelsPaymentResponse;
}

export interface AddressesPaymentResponse {
    delivery: DeliveryPaymentResponse;
    invoice:  DeliveryPaymentResponse;
}

export interface DeliveryPaymentResponse {
    id_customer:     string;
    id_manufacturer: string;
    id_supplier:     string;
    id_warehouse:    string;
    id_country:      string;
    id_state:        string;
    alias:           string;
    company:         string;
    lastname:        string;
    firstname:       string;
    vat_number:      string;
    address1:        string;
    address2:        string;
    postcode:        string;
    city:            string;
    other:           string;
    phone:           string;
    phone_mobile:    string;
    dni:             string;
    date_add:        string;
    date_upd:        string;
    id:              number;
    formatted:       string;
}

export interface AmountsPaymentResponse {
    subtotals: SubtotalsPaymentResponse;
    totals:    TotalsPaymentResponse;
}

export interface SubtotalsPaymentResponse {
    products:      DiscountsPaymentResponse;
    discounts:     DiscountsPaymentResponse;
    shipping:      DiscountsPaymentResponse;
    tax:           DiscountsPaymentResponse;
    gift_wrapping: DiscountsPaymentResponse;
}

export interface DiscountsPaymentResponse {
    type:   string;
    label:  null | string;
    amount: number | null | string;
    value:  string;
}

export interface TotalsPaymentResponse {
    total:               DiscountsPaymentResponse;
    total_paid:          DiscountsPaymentResponse;
    total_including_tax: DiscountsPaymentResponse;
    total_excluding_tax: DiscountsPaymentResponse;
}

export interface CarrierPaymentResponse {
    id_reference:         string;
    name:                 string;
    is_free:              string;
    url:                  string;
    shipping_handling:    string;
    shipping_external:    string;
    range_behavior:       string;
    shipping_method:      number;
    max_width:            string;
    max_height:           string;
    max_depth:            string;
    max_weight:           string;
    grade:                string;
    external_module_name: string;
    is_module:            string;
    need_range:           string;
    position:             string;
    delay:                string;
    id:                   number;
}

export interface DetailsPaymentResponse {
    id:            number;
    reference:     string;
    order_date:    string;
    details_url:   string;
    reorder_url:   string;
    invoice_url:   string;
    gift_message:  string;
    is_returnable: number;
    payment:       string;
    module:        string;
    recyclable:    boolean;
    is_valid:      string;
    is_virtual:    boolean;
    shipping:      { [key: string]: string }[];
}

export interface HistoryPaymentResponse {
    current: { [key: string]: null | string };
}

export interface LabelsPaymentResponse {
    tax_short: string;
    tax_long:  string;
}

export interface Products {
    [key: string]: ProductCart;
}
export interface Cover {
    bySize:             BySize;
    small:              Large;
    medium:             Large;
    large:              Large;
    legend:             string;
    id_image:           string;
    cover:              string;
    position:           string;
    associatedVariants: any[];
}

export interface BySize {
    small_default:  Large;
    cart_default:   Large;
    home_default:   Large;
    medium_default: Large;
    large_default:  Large;
}

export interface Large {
    url:    string;
    width:  number;
    height: number;
}

export interface Image {
    id:           number;
    id_image:     string;
    id_product:   string;
    position:     string;
    cover:        string;
    legend:       { [key: string]: string };
    image_format: string;
    source_index: string;
    id_shop_list: any[];
    force_id:     boolean;
}

export interface TaxCalculator {
    taxes:              any[];
    computation_method: number;
}
